# This is the configuration used to check the rubocop source code.

AllCops:
  NewCops: disable
  Exclude:
    - spec/support/spec_helper.rb
    - spec/rails_helper.rb
    - db/**/*
    - docs/**/*
    - config/**/*
    - bin/**/*

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 99
  Exclude:
    - spec/**/*
    - config/routes.rb

Layout/HashAlignment:
  Enabled: true
  Exclude:
    - lib/tasks/auto_annotate_models.rake

HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - lib/tasks/auto_annotate_models.rake

Style/FrozenStringLiteralComment:
  Enabled: false

# rubocop-rspec custom configurations

require:
  - rubocop-rspec
  - rubocop-rails

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/ExampleLength:
  Exclude:

RSpec/AnyInstance:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 3

Rails/RakeEnvironment:
  Exclude:
    - lib/tasks/auto_annotate_models.rake