# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development: &development
  secret_key_base: 896e9c02c06400af4cb78b9bc4d02d9b0364f3aed9e4f879017f9bd27c08b07fb10617c1469786758846714189c331eb4ebd885999fdc6de56ef38a5b7c5246b
  sidekiq_username: <%= ENV['SIDEKIQ_USERNAME'] %>
  sidekiq_password: <%= ENV['SIDEKIQ_PASSWORD'] %>
  sidekiq_queue_size: <%= ENV['SIDEKIQ_QUEUE_SIZE'] %>
  sidekiq_queue_latency: <%= ENV['SIDEKIQ_QUEUE_LATENCY'] %>
  current_host: 'localhost:3000'
  rack_attack_enabled: false
  rack_attack_max_requests_per_second: <%= ENV.fetch('RACK_ATTACK_MAX_REQUESTS_PER_SECOND', 5) %>
  request_retries: <%= ENV.fetch('REQUEST_RETRIES', 3) %>

test: &test
  <<: *development

# Do not keep production secrets in the repository, instead read values from the environment.
production: &production
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  sidekiq_username: <%= ENV['SIDEKIQ_USERNAME'] %>
  sidekiq_password: <%= ENV['SIDEKIQ_PASSWORD'] %>
  sidekiq_queue_size: <%= ENV['SIDEKIQ_QUEUE_SIZE'] %>
  sidekiq_queue_latency: <%= ENV['SIDEKIQ_QUEUE_LATENCY'] %>
  current_host: <%= ENV['CURRENT_HOST'] %>
  rack_attack_enabled: <%= ENV.fetch('RACK_ATTACK_ENABLED', true) %>
  rack_attack_max_requests_per_second: <%= ENV.fetch('RACK_ATTACK_MAX_REQUESTS_PER_SECOND', 5) %>
  request_retries: <%= ENV.fetch('REQUEST_RETRIES', 3) %>
  cors_origins: <%= ENV['CORS_ORIGINS'] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  rollbar_environment: <%= ENV['ROLLBAR_ENVIRONMENT'] %>

staging:
    <<: *production
