#!/usr/bin/env bash
#
# Rails console script that can be run on AWS Elastic Beanstalk.
#
# Run this script from the app dir (/var/app/current) as root (sudo script/aws-console)

set -xe

export $(cat /opt/elasticbeanstalk/deployment/env | xargs)

cd /var/app/current

su -s /bin/bash -c "bundle exec rails c"
