#!/usr/bin/env ruby

# Changes App name
app_name = ARGV.first
system('rm -rf tmp')
system('rm -rf log')
system('rm -rf .travis.yml')
system('rm -rf config/database.travis.yml')
system('rm -rf coverage')
puts "Setting App name: #{app_name}..."
Dir.glob('**/*', File::FNM_DOTMATCH)
   .reject { |f| f.match('\.git(?!hub)') || f['script'] }.each do |name|
  next unless File.file?(name) && name != '.DS_Store'

  out = File.read(name).gsub('rails-api-bootstrap', app_name)
  out = out.gsub('RAILS_API_BOOTSTRAP', app_name.tr('-', '_').upcase)

  capitalized_app_name = app_name.tr('-', '_').split('_').map(&:capitalize)
  out = out.gsub('RailsApiBootstrap', capitalized_app_name.join)
  out = out.gsub('Rails Api Bootstrap', capitalized_app_name.join(' '))

  File.open(name, 'w+') do |f|
    f << out
  end
end

# Removes Gitter and LICENSE
readme = File.read('README.md')
readme.gsub!('Kickoff for Rails API applications.', '')
readme.gsub!('- Run ./script/bootstrap app_name where app_name is your application name.', '')
readme.gsub!(/\n\n## License((.)*(\n)*)*$/, '')
File.open('README.md', 'w') { |file| file.puts(readme) }

puts 'Done'
